### PR TITLE
Bump theme

### PR DESCRIPTION
**Pull request by hintxiv**
* Added the /jobs redirect as in `exampleSite`.
* Split `package.json` from glam to add scripts which pull content from `content/` rather than `exampleSite/content/` (also changed the name, description, etc).

### CODE REVIEW

**Review by redshadowhero — CHANGES_REQUESTED** [review]
I wouldn't duplicate the package.json. I would just modify glam's one – that way if the theme's package.json updates dependencies and etc, there's only one file to change.

**Comment by hintxiv** [comment]
I think in the medium-long term we're going to want a separate package.json anyway to accommodate features that aren't present in the theme, but I'll leave it out in the interest of getting updates live. We can revisit later.

**Comment by nonowazu** [comment]
I'm curious what features would require a separate package.json – the major issues would be if glam updated a package and it got missed in a future glam bump.

**Comment by lailleo** [comment]
@rexatlanti Can you give a cursory glance at this too?

**Pull request merged**
